langugage: node_js
node_js:
  - "stable"

sudo: required

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

stages:
  - test

jobs:
  include:
    - stage: test
      name: test
      if: tag IS NOT present
      install:
        - docker run -d --name redis -p 6379:6379 redis:latest
        - docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local
        - docker run -itd -v "$(pwd):/app" --name test-app --link redis:redis --link dynamodb:dynamodb node:lts
        - docker exec -it -w /app test-app bash -c "npm install"
      script:
        - docker exec -it -w /app test-app bash -c "npm test"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f "$(pwd)/coverage/coverage-final.json"
    
    - stage: build
      name: build
      if: branch IN (todo) #TODO
      install:
        - sudo apt-get install python3-pip 
        - sudo pip3 install awscli
      script:
        - $(aws ecr get-login --no-include-email --region ap-northeast-2)
        - GIT_REVISION=$TRAVIS_COMMIT make build
      after_success:
        - docker push <KCP_AWS_REGISTRY>:$TRAVIS_COMMIT