langugage: node_js
node_js:
  - "stable"

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

stages:
  - test
  - build
  - deploy
  - docs

jobs:
