#%RAML 1.0
title: RIDI KCP PAYMENT MICROSERVICE API
version: v1
baseUrl: //api.kcp.ridi.io ??
mediaType: application/json
types:
  AuthKeyRequest:
    description: 결제를 위한 카드 인증(배치)키 요청
    type: object
    properties:
      mode:
        description: 요청모드        
        type: string
        required: true
        pattern: dev|prd|ptx
      card_no:
        description: 카드번호 16자리        
        type: string
        required: true
      card_expiry_date:
        description: 카드유효기간 연월(YYMM) 4자리
        type: string
        required: true
      card_tax_no:
        description: 카드인증번호 - 개인: 생년월일6자리, 법인: 사업자번호10자리
        type: string
        required: true
      card_password:
        description: 카드비밀번호 앞2자리
        type: string
        required: true
        
  PaymentAuthKeyResult:
    type: object
    properties: 
      code: string
      is_success: boolean
      message: string
      card_code: string
      card_name: string
      card_bank_code: string
      van_tx_id: string
      card_bin_type_01: string
      batch_key: string
      join_code: string
  PaymentApprovalResult:
    type: object
    properties: 
      code: string
      is_success: boolean
      message: string
      en_message: string
      trace_no: string
      pay_method: string
      order_no: string
      card_code: string
      card_name: string
      acqu_code: string
      acqu_name: string
      card_no: string
      mcht_tax_no: string
      mall_tax_no: string
      ca_order_id: string
      tno: string
      amount: number
      card_amount: number
      coupon_amount: number
      is_escrow: boolean
      van_code: string
      app_time: string
      van_app_time: string
      app_no: string
      bizx_no: string
      quota: number
      is_interest_free: boolean
      pg_tx_id: string
      tax_flag: string
      tax_amount: number
      tax_free_amount: number
      vat_amount: number
      is_partial_cancel: boolean
      card_bin_type_01: string
      card_bin_type_02: string
      card_bin_bank_code: string
      join_code: string
  PaymentCancellationResult:
    type: object
    properties: 
      code: string
      is_success: boolean
      message: string
      en_message: string
      trace_no: string
      pay_method: string
      order_no: string
      card_code: string
      card_name: string
      acqu_code: string
      acqu_name: string
      card_no: string
      mcht_tax_no: string
      mall_tax_no: string
      ca_order_id: string
      tno: string
      amount: number
      card_amount: number
      coupon_amount: number
      is_escrow: boolean
      cancel_gubun: string
      van_code: string
      app_time: string
      van_app_time: string
      cancel_time: string
      app_no: string
      bizx_no: string
      quota: number
      is_interest_free: boolean
      pg_tx_id: string
/kcp:
  /health:
    get:
      responses:
        200:
          body:
            application/json:
              type: string
                                
  /payments/auth-key:
      post:
  body:
  application/json:
  type: