version: "3"

services:
  app:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/kcp-http-proxy:${GIT_REVISION}
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      APP_ENV: ${APP_ENV}
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: ${APP_ENV}.kcp-http-proxy
        awslogs-stream-prefix: ${APP_ENV}.kcp-http-proxy
