version: "3"

services:
  dynamodb:
    container_name: ridi_kcp_api_db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - dynamodbdata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "."]

  application:
    container_name: ridi_kcp_api
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      APP_MODE: development
      APP_PORT: 3000
      KCP_SITE_CODE: test
      KCP_SITE_KEY: test
      KCP_GROUP_ID: test
      KCP_TAX_DEDUCTION_SITE_CODE: test
      KCP_TAX_DEDUCTION_SITE_KEY: test
      KCP_TAX_DEDUCTION_GROUP_ID: test        
      SENTRY_DSN: https://d460d631817d4b7e9d917706eea1f538@sentry.io/1307885
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      AWS_LOG_GROUP: test.ridi-kcp.api
      AWS_LOG_STREAM_NAME: app
      AWS_DYNAMO_DB_ENDPOINT: http://dynamodb:8000
    ports:
      - 3000:3000
    links:
      - dynamodb
    command: npm run prod
    
volumes:
  dynamodbdata: