version: '3'

services:
  dynamodb:
    container_name: test-db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - test-network
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  application:
    container_name: test-app
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      APP_ENV: dev
      PORT: 3000      
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2      
      AWS_DYNAMO_DB_ENDPOINT: http://dynamodb:8000
    ports:
      - 3000:3000
    depends_on:
      - dynamodb
    networks:
      - test-network
    command: >
      bash -c 'npm install &&
               npm test'

networks:
  test-network:
    driver: bridge