version: '3'

services:
  app:
    build: .
    environment:
      APP_ENV: dev
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    command: ['bash', '-c', 'yarn run init-db && yarn test']

  dynamodb:
    image: amazon/dynamodb-local
