version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      APP_ENV: dev
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      REDIS_HOST: redis
    depends_on:
      - redis
      - dynamodb
    command: ['bash', '-c', 'npm test']
  redis:
    image: redis:latest
  dynamodb:
    image: amazon/dynamodb-local
