version: '3'

services:
  dynamodb:
    container_name: test_ridi_kcp_http_proxy_db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - test_ridi_kcp_http_proxy
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  application:
    container_name: test_ridi_kcp_http_proxy
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      PROFILE: dev
      PORT: 3000
      KCP_SITE_CODE: test
      KCP_SITE_KEY: test
      KCP_GROUP_ID: test
      kcp_tax_deduction_site_code: test
      kcp_tax_deduction_site_key: test
      kcp_tax_deduction_group_id: test        
      SENTRY_DSN: your_sentry_dsn
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      AWS_LOG_GROUP: test.ridi-kcp.api
      AWS_LOG_STREAM_NAME: app
      AWS_DYNAMO_DB_ENDPOINT: http://dynamodb:8000
    ports:
      - 3000:3000
    depends_on:
      - dynamodb
    networks:
      - test_ridi_kcp_http_proxy
    command: >
      bash -c 'npm run build && npm run test'

networks:
  test_ridi_kcp_http_proxy:
    driver: bridge