version: "3"

services:
  dynamo:
    container_name: ridi_kcp_api_db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "."]

  web:
    container_name: ridi_kcp_api
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    environment:
        KCP_SITE_CODE: test
        KCP_SITE_KEY: test
        KCP_GROUP_ID: test
        KCP_TAX_DEDUCTION_SITE_CODE: test
        KCP_TAX_DEDUCTION_SITE_KEY: test
        KCP_TAX_DEDUCTION_GROUP_ID: test
        APP_MODE: development
        SENTRY_DSN: https://d460d631817d4b7e9d917706eea1f538@sentry.io/1307885
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_REGION: ap-northeast-2
        AWS_LOG_GROUP: test.ridi-kcp.api
        AWS_LOG_STREAM_NAME: app
        AWS_DYNAMO_DB_ENDPOINT: http://dynamo:8000
    ports:
      - 3000:3000
    links:
      - dynamo
    command: npm run dev