version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '/home/dynamodblocal/data']
    volumes:
     - ./data/dynamodb:/home/dynamodblocal/data

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 80
    environment:
      APP_ENV: dev
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    command: ['bash', '-c', 'npm run init-db && npm start']
