version: '3'

services:
  dynamodb:
    container_name: kcp-http-proxy-db
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - kcp-http-proxy-net
    working_dir: /home/dynamodblocal
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '.']

  application:
    container_name: kcp-http-proxy
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      PROFILE: dev
      PORT: 3000
      KCP_SITE_CODE: test
      KCP_SITE_KEY: test
      KCP_GROUP_ID: test
      KCP_TAX_DEDUCTION_SITE_CODE: test
      KCP_TAX_DEDUCTION_SITE_KEY: test
      KCP_TAX_DEDUCTION_GROUP_ID: test        
      SENTRY_DSN: your_sentry_dsn
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      AWS_LOG_GROUP: test.ridi-kcp.api
      AWS_LOG_STREAM_NAME: app
      AWS_DYNAMO_DB_ENDPOINT: http://dynamodb:8000
    ports:
      - 3000:3000
    depends_on:
      - dynamodb
    networks:
      - kcp-http-proxy-net
    command: >
      bash -c 'npm i pm2 -g &&
               npm ci &&
               pm2-runtime --name kcp-http-proxy npm -- start'
    
networks:
  kcp-http-proxy-net:
    driver: bridge