import { attribute, autoGeneratedHashKey, rangeKey, table } from "@aws/dynamodb-data-mapper-annotations";
import { CommandType } from "../../application/command/CommandType";
import { Mode } from "../../common/config";
import { AbstractPaymentResult } from "../result/AbstractPaymentResult";

@table("payment_requests")
export class PaymentRequestEntity {
    @autoGeneratedHashKey()
    id?: string;
    
    @attribute()
    command_type?: CommandType;

    @attribute()
    mode?: Mode;

    @attribute()
    key: string;

    @rangeKey({ defaultProvider: () => new Date() })
    created_at: Date;

    @attribute()
    updated_at: Date;

    @attribute()
    results?: Array<AbstractPaymentResult>;
}